INFO _internal.py:97  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1761 Exception on /user/register [GET]
Traceback (most recent call last):
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_session/sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/redis/client.py", line 1472, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/home/ubantu/.virtualenvs/flask/local/lib/python2.7/site-packages/redis/connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
INFO _internal.py:97 127.0.0.1 - - [28/Mar/2019 15:19:17] "GET /user/register HTTP/1.1" 500 -
